name: alangfiles blog
markdown: redcarpet
highlighter: pygments
description: "A little something about the author, and where his mind wanders"
url: "alangfiles.github.io/blog"
permalink: /posts/:title
