# Site settings
title: Alan Files
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A description of the author, and the work he's done and is doing.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://alangfiles.github.io" # the base hostname & protocol for your site
twitter_username: alangfiles
github_username:  alangfiles

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext